name: Woody
options:
  carthageExecutablePath: 'mint run carthage carthage'
targets:
  Woody:
    type: application
    platform: iOS
    deploymentTarget: 11.0
    sources: [Woody]
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.Woody.ios
      SWIFT_VERSION: '5.0'
    postCompileScripts:
      - script: |
          if mint list | grep -q 'SwiftLint'; then
          mint run SwiftLint swiftlint autocorrect
          mint run SwiftLint swiftlint
          else
          echo "warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint"
          fi
        name: Swiftlint
  WoodyTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: '10.0'
    sources: [WoodyTests]
    dependencies:
      - target: Woody
